ik_solver_msgs/IkTarget[] targets

string[] seed_joint_names
uint32 max_number_of_solutions # if zero, use default.
uint32 stall_iterations # if zero, use default.

uint8 PARALLELIZE_DEFAULT=0
uint8 PARALLELIZE_FORCE=1
uint8 PARALLELIZE_DISABLE=2

uint8 parallelize

uint8 UPDATE_RECURSIVELY_SEEDS_DEFAULT=0
uint8 UPDATE_RECURSIVELY_SEEDS_FORCE=1
uint8 UPDATE_RECURSIVELY_SEEDS_DISABLE=2
uint8 update_recursively_seeds


---
ik_solver_msgs/IkSolution[] solutions
string[] joint_names
